/**
 * The frozen row contract for /naam.
 *
 * DESIGN.md §4 (honesty vocabulary) and P9 (proof over claim) are the reason
 * this file is shaped the way it is. The page shows two kinds of statement about
 * a name — what the document says, and what we worked out — and DESIGN.md's
 * answer to "how does a visitor tell them apart" is the type system, not a
 * fourth badge word: mono is the voice of data (P5), prose is the voice of the
 * site. That distinction only survives contact with the code if the data itself
 * knows which half a field belongs to. Hence two interfaces:
 *
 *   NaamDocumentFields — verbatim or structural, lifted out of
 *                        Boy_Name_Candidates.pdf. NEVER mutate these. If one of
 *                        them is wrong, the document is wrong, and the honest
 *                        move is to say so, not to correct it silently.
 *   NaamDerivedFields  — ours. Tidied, transliterated, tagged, scored. Every one
 *                        of these is an interpretation and may be argued with.
 *
 * NaamRow is the flat union of the two, because that is what a 6,715-row JSON
 * payload and a card component both want to read. The separation is preserved
 * at the type level so nothing downstream has to remember which is which.
 *
 * Generated by scripts/naam/build-dataset.mjs. Do not hand-edit the artifacts.
 */

/** B is Bishal, S is Sneha, V is here because Nepali turns व into ब anyway. */
export type NaamLetter = 'B' | 'S' | 'V'

/** The document only ever offers 1, 2 or 3. */
export type NaamSyllables = 1 | 2 | 3

/**
 * The document's own two-tier layout: within each letter and syllable count a
 * "Shortlist — attested names & evocative meanings" comes first, then "More".
 */
export type NaamTier = 'shortlist' | 'more'

/** The document's Src column. V = Vedic, C = Classical, T = Theravada. */
export type NaamSource = 'V' | 'C' | 'T'

export const NAAM_SOURCE_LABEL: Readonly<Record<NaamSource, string>> = {
  V: 'Vedic',
  C: 'Classical',
  T: 'Theravada',
}

/**
 * The document's four badge glyphs, spelled out.
 *   N  attested as a deity/person/epithet name
 *   +  evocative meaning
 *   f? grammatically feminine ending ("say it aloud to judge" — the document's
 *      own instruction, and the reason /naam is built around sound)
 *   !  harder consonant cluster
 */
export interface NaamBadges {
  attested: boolean
  evocative: boolean
  feminineEnding: boolean
  hardCluster: boolean
}

/**
 * How well the PDF's own B-form reads out loud. Ours, not the document's.
 * 'awkward' when the B-form opens on a cluster (Bl-, Br-, Bv-, By-, or B +
 * two consonants) or the row carries the document's ! badge. null for non-V
 * rows, which have no B-form to judge.
 *
 * This exists so that "use judgment, not a hardcoded rule" about the व→ब swap
 * becomes a field a matcher and a model can reason over, instead of a vibe.
 */
export type NaamBFormQuality = 'clean' | 'awkward'

/**
 * How much to trust `devanagari`. The PDF contains zero Devanagari, so today
 * every row is 'derived' — a rule-based rendering of a lossy romanization.
 * The union has a second member so hand-checked forms can be marked later
 * without a schema change.
 */
export type NaamDevanagariConfidence = 'derived' | 'checked'

/**
 * The theme lexicon. Fixed and closed, in this order — `themeMask` is a bitmask
 * over these indices, so appending is safe and reordering is not.
 *
 * The first fifteen are the plan's list. The last four were added because the
 * document's own gold rows (attested AND evocative) kept landing on senses the
 * first fifteen had no word for: kings and princes, purity, speed, and truth.
 */
export const NAAM_THEMES = [
  'light',
  'strength',
  'wisdom',
  'compassion',
  'joy',
  'auspicious',
  'sky',
  'water',
  'earth',
  'sound',
  'protection',
  'lotus',
  'peace',
  'deity',
  'monk',
  'royal',
  'purity',
  'swift',
  'truth',
] as const

export type NaamTheme = (typeof NAAM_THEMES)[number]

/** Bit for a theme in `NaamRow.themeMask`. */
export function naamThemeBit(theme: NaamTheme): number {
  return 1 << NAAM_THEMES.indexOf(theme)
}

/** Bitmask for a set of themes. */
export function naamThemeMask(themes: readonly NaamTheme[]): number {
  let mask = 0
  for (const t of themes) mask |= naamThemeBit(t)
  return mask
}

/* ────────────────────────────────────────────────────────────────────────────
   FROM THE DOCUMENT — verbatim or structural. Never altered.
   ──────────────────────────────────────────────────────────────────────────── */

export interface NaamDocumentFields {
  /**
   * Stable slug of the primary latin form, lowercased, deduped with -2 / -3 in
   * document order. Ours in the sense that we minted it, document-sourced in the
   * sense that it is a pure function of `latin` and position — it never moves.
   */
  id: string

  /**
   * The source spelling, exactly as printed. For a V row this is the V-form,
   * which is the form the document indexes on. NEVER mutated — the page may
   * *display* the B-form by preference, but it does not rewrite the source.
   */
  latin: string

  /** The PDF's own B-form for V rows (its column header offers it). null otherwise. */
  bVariant: string | null

  letter: NaamLetter
  syllables: NaamSyllables
  tier: NaamTier

  /** Subset of ['V','C','T'], in that order. */
  sources: NaamSource[]

  badges: NaamBadges

  /** The document's Meaning column, verbatim and untouched. Never render this in prose type. */
  sourceGloss: string

  /** PDF page, 1..172. This is the citation. */
  page: number
}

/* ────────────────────────────────────────────────────────────────────────────
   OURS — derived, interpretive, arguable. Render in body type, never in mono.
   ──────────────────────────────────────────────────────────────────────────── */

export interface NaamDerivedFields {
  /**
   * A tidy one-line read of `sourceGloss`. Conservative by construction:
   * Monier-Williams abbreviations expanded only where the corpus makes them
   * unambiguous, citation debris dropped, deity names capitalized, long lists
   * cut at a clause boundary with an ellipsis. It never changes or invents
   * meaning; where tidying would have, the original is kept.
   */
  gloss: string

  /** true when `gloss === sourceGloss`, i.e. we changed nothing. */
  glossIsVerbatim: boolean

  /**
   * Rule-based transliteration of `latin`. APPROXIMATE — the PDF contains zero
   * Devanagari, and the romanization is lossy about vowel length, retroflexion
   * and vocalic ṛ. Always shown beside the Latin, never instead of it.
   */
  devanagari: string

  /**
   * The same transliteration run over `bVariant`, so a card showing the B
   * spelling can show the B script. null on rows with no B-form.
   *
   * It exists because the swap is the page's whole joke and it was not
   * happening in the one script the joke is about: every row carried a single
   * Devanagari form derived from `latin` — the V-form — while the page's
   * display preference defaults to B, so a card read "वस्तु / Bastu".
   */
  devanagariB: string | null

  devanagariConfidence: NaamDevanagariConfidence

  /**
   * Syllables of `latin` for the sound rail, digraph-aware, closed after each
   * vowel nucleus.
   *
   * `syllableSplit.length === syllables` for 6,691 of 6,715 rows. The 24
   * exceptions are listed in src/generated/naam-facts.ts and are the document's
   * error, not ours: its syllable counts were computed on a diacritic-stripped
   * form, so names carrying a Pali retroflex ḷ or a Sanskrit vocalic ṛ (Veḷu,
   * Biḷāra, Śruta-ṛṣi) lost a nucleus. The split is authoritative for the rail;
   * `syllables` stays authoritative for filtering, because it is the document's.
   */
  syllableSplit: string[]

  /** Keyword-derived tags over `sourceGloss`. Subset of NAAM_THEMES. */
  themes: NaamTheme[]

  /** Bitmask of `themes` over NAAM_THEMES indices, for cheap client-side scoring. */
  themeMask: number

  /** Lowercased latin + bVariant + gloss, for substring search. */
  searchKey: string

  /** See NaamBFormQuality. null for non-V rows. */
  bFormQuality: NaamBFormQuality | null
}

export interface NaamRow extends NaamDocumentFields, NaamDerivedFields {}

/** A row is "gold" when the document flags it both attested and evocative. */
export function isNaamGold(row: NaamRow): boolean {
  return row.badges.attested && row.badges.evocative
}

/**
 * The form to show first. The family's preference is the B spelling, but this
 * is a display choice: `latin` is never mutated, and which spelling a visitor
 * recommended is recorded separately.
 */
export function naamPreferredForm(row: NaamRow, preferB: boolean): string {
  return preferB && row.bVariant ? row.bVariant : row.latin
}

/**
 * The Devanagari that goes with `naamPreferredForm(row, preferB)`. Same choice,
 * same moment — a card that shows Bastu must show बस्तु, not वस्तु.
 */
export function naamPreferredDevanagari(row: NaamRow, preferB: boolean): string {
  return preferB && row.bVariant && row.devanagariB ? row.devanagariB : row.devanagari
}
